version: '3.7'
services:
  web:
    image: flask
    build: .
    ports:
      - "8080:$FLASK_RUN_PORT"
    environment:
      - FLASK_RUN_PORT= $FLASK_RUN_PORT
      - FLASK_ENV=development
    volumes:
      - "./app.py:/code/app.py"
  redis:
    image: "redis:alpine"




